//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoderZone.Extensions.OptionsPackage {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class RemarkerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RemarkerSettings defaultInstance = ((RemarkerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RemarkerSettings())));
        
        public static RemarkerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string FontFamily {
            get {
                return ((string)(this["FontFamily"]));
            }
            set {
                this["FontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float GiantFactor {
            get {
                return ((float)(this["GiantFactor"]));
            }
            set {
                this["GiantFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.6667")]
        public float HugeFactor {
            get {
                return ((float)(this["HugeFactor"]));
            }
            set {
                this["HugeFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.3333")]
        public float LargeFactor {
            get {
                return ((float)(this["LargeFactor"]));
            }
            set {
                this["LargeFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.85")]
        public float SmallFactor {
            get {
                return ((float)(this["SmallFactor"]));
            }
            set {
                this["SmallFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public float TinyFactor {
            get {
                return ((float)(this["TinyFactor"]));
            }
            set {
                this["TinyFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.55")]
        public float MicroFactor {
            get {
                return ((float)(this["MicroFactor"]));
            }
            set {
                this["MicroFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Todo")]
        public string Task01 {
            get {
                return ((string)(this["Task01"]));
            }
            set {
                this["Task01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hack")]
        public string Task02 {
            get {
                return ((string)(this["Task02"]));
            }
            set {
                this["Task02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Question")]
        public string Task03 {
            get {
                return ((string)(this["Task03"]));
            }
            set {
                this["Task03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bug")]
        public string Task04 {
            get {
                return ((string)(this["Task04"]));
            }
            set {
                this["Task04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Note")]
        public string Task05 {
            get {
                return ((string)(this["Task05"]));
            }
            set {
                this["Task05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task06 {
            get {
                return ((string)(this["Task06"]));
            }
            set {
                this["Task06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task07 {
            get {
                return ((string)(this["Task07"]));
            }
            set {
                this["Task07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task08 {
            get {
                return ((string)(this["Task08"]));
            }
            set {
                this["Task08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task09 {
            get {
                return ((string)(this["Task09"]));
            }
            set {
                this["Task09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task10 {
            get {
                return ((string)(this["Task10"]));
            }
            set {
                this["Task10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold01 {
            get {
                return ((bool)(this["TaskBold01"]));
            }
            set {
                this["TaskBold01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold02 {
            get {
                return ((bool)(this["TaskBold02"]));
            }
            set {
                this["TaskBold02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold03 {
            get {
                return ((bool)(this["TaskBold03"]));
            }
            set {
                this["TaskBold03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold04 {
            get {
                return ((bool)(this["TaskBold04"]));
            }
            set {
                this["TaskBold04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold05 {
            get {
                return ((bool)(this["TaskBold05"]));
            }
            set {
                this["TaskBold05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold06 {
            get {
                return ((bool)(this["TaskBold06"]));
            }
            set {
                this["TaskBold06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold07 {
            get {
                return ((bool)(this["TaskBold07"]));
            }
            set {
                this["TaskBold07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold08 {
            get {
                return ((bool)(this["TaskBold08"]));
            }
            set {
                this["TaskBold08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold09 {
            get {
                return ((bool)(this["TaskBold09"]));
            }
            set {
                this["TaskBold09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskBold10 {
            get {
                return ((bool)(this["TaskBold10"]));
            }
            set {
                this["TaskBold10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000ff")]
        public string TaskColor01 {
            get {
                return ((string)(this["TaskColor01"]));
            }
            set {
                this["TaskColor01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("008000")]
        public string TaskColor02 {
            get {
                return ((string)(this["TaskColor02"]));
            }
            set {
                this["TaskColor02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff00d6")]
        public string TaskColor03 {
            get {
                return ((string)(this["TaskColor03"]));
            }
            set {
                this["TaskColor03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff0000")]
        public string TaskColor04 {
            get {
                return ((string)(this["TaskColor04"]));
            }
            set {
                this["TaskColor04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8b0807")]
        public string TaskColor05 {
            get {
                return ((string)(this["TaskColor05"]));
            }
            set {
                this["TaskColor05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string TaskColor06 {
            get {
                return ((string)(this["TaskColor06"]));
            }
            set {
                this["TaskColor06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string TaskColor07 {
            get {
                return ((string)(this["TaskColor07"]));
            }
            set {
                this["TaskColor07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string TaskColor08 {
            get {
                return ((string)(this["TaskColor08"]));
            }
            set {
                this["TaskColor08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string TaskColor09 {
            get {
                return ((string)(this["TaskColor09"]));
            }
            set {
                this["TaskColor09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string TaskColor10 {
            get {
                return ((string)(this["TaskColor10"]));
            }
            set {
                this["TaskColor10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface01 {
            get {
                return ((string)(this["TaskTypeface01"]));
            }
            set {
                this["TaskTypeface01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface02 {
            get {
                return ((string)(this["TaskTypeface02"]));
            }
            set {
                this["TaskTypeface02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface03 {
            get {
                return ((string)(this["TaskTypeface03"]));
            }
            set {
                this["TaskTypeface03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface04 {
            get {
                return ((string)(this["TaskTypeface04"]));
            }
            set {
                this["TaskTypeface04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface05 {
            get {
                return ((string)(this["TaskTypeface05"]));
            }
            set {
                this["TaskTypeface05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface06 {
            get {
                return ((string)(this["TaskTypeface06"]));
            }
            set {
                this["TaskTypeface06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface07 {
            get {
                return ((string)(this["TaskTypeface07"]));
            }
            set {
                this["TaskTypeface07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface08 {
            get {
                return ((string)(this["TaskTypeface08"]));
            }
            set {
                this["TaskTypeface08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface09 {
            get {
                return ((string)(this["TaskTypeface09"]));
            }
            set {
                this["TaskTypeface09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string TaskTypeface10 {
            get {
                return ((string)(this["TaskTypeface10"]));
            }
            set {
                this["TaskTypeface10"] = value;
            }
        }
    }
}
