//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoderZone.Extensions.Options.Itboy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoderZone.Extensions.Options.Itboy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator Tasks.
        /// </summary>
        internal static string VALIDATOR_ACTIONLIST_TASKS {
            get {
                return ResourceManager.GetString("VALIDATOR_ACTIONLIST_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Validation Informations.
        /// </summary>
        internal static string VALIDATOR_ACTIONLIST_TASKS_CLEARVALIDATIONINFOS {
            get {
                return ResourceManager.GetString("VALIDATOR_ACTIONLIST_TASKS_CLEARVALIDATIONINFOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string VALIDATOR_CATEGORY_ACTION {
            get {
                return ResourceManager.GetString("VALIDATOR_CATEGORY_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string VALIDATOR_CATEGORY_BEHAVIOR {
            get {
                return ResourceManager.GetString("VALIDATOR_CATEGORY_BEHAVIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Provider.
        /// </summary>
        internal static string VALIDATOR_CATEGORY_ERRORPROVIDER {
            get {
                return ResourceManager.GetString("VALIDATOR_CATEGORY_ERRORPROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string VALIDATOR_CATEGORY_VALIDATION {
            get {
                return ResourceManager.GetString("VALIDATOR_CATEGORY_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear all validation infomation from current binded controls?.
        /// </summary>
        internal static string VALIDATOR_CLEARWARNING {
            get {
                return ResourceManager.GetString("VALIDATOR_CLEARWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feild value compare fail..
        /// </summary>
        internal static string VALIDATOR_DEFAULT_COMPAREMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DEFAULT_COMPAREMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feild do not follow purpose of inputting..
        /// </summary>
        internal static string VALIDATOR_DEFAULT_CUSTOMMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DEFAULT_CUSTOMMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feild value out of range..
        /// </summary>
        internal static string VALIDATOR_DEFAULT_RANGEMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DEFAULT_RANGEMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feild do not match it is content..
        /// </summary>
        internal static string VALIDATOR_DEFAULT_REGULAREXPRESSIONMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DEFAULT_REGULAREXPRESSIONMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feild is required..
        /// </summary>
        internal static string VALIDATOR_DEFAULT_REQUIREMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DEFAULT_REQUIREMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate all configured validation information controls which lay onto the specified container, when the container is closing..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_BEHAVIOR_FORM {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_BEHAVIOR_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation mode. This mode should be combined with the follow value. FocusChange: Can change to next control when validation fail. Submit:Validate control when user submit..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_BEHAVIOR_MODE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_BEHAVIOR_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rate in milliseconds at which the error icon blinks..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_ERRORPROVIDER_BLINKRATE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_ERRORPROVIDER_BLINKRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether the error icon blinks when an error is set..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_ERRORPROVIDER_BLINKSTYLE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_ERRORPROVIDER_BLINKSTYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon used to indicate an error..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_ERRORPROVIDER_ICON {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_ERRORPROVIDER_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the component should draw right-to-left for RTL languages..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_ERRORPROVIDER_RIGHTTOLEFT {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_ERRORPROVIDER_RIGHTTOLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when validate, it required set &quot;Custom&quot; validation type flag..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_EVENT_CUSTOMVALIDATION {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_EVENT_CUSTOMVALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify compared control..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_COMPAREDCONTROL {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_COMPAREDCONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a message to been show when control violate compare rule(not match compare operation to compared control). Keyword: {$DataType} represent DataType, {$CompareOperator} represent CompareOperator..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_COMPAREMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_COMPAREMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how comparing to compared control..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_COMPAREOPERATOR {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_COMPAREOPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a message to been show when control violate custom rule(implement Validating event in Validator)..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_CUSTOMMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_CUSTOMMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify data prototype for current control&apos;s text..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_DATATYPE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_DATATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a message to been show when control violate range rule(text value out of range). Keyword: {$RangeOfLowerBound} represent RangeOfLowerBound; {$RangeOfUpperBound} represent RangeOfUpperBound..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_RANGEMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_RANGEMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify lower bound of control value..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_RANGEOFLOWERBOUND {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_RANGEOFLOWERBOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify upper bound of control value..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_RANGEOFUPPERBOUND {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_RANGEOFUPPERBOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicfy regular expression for validation. This property only valid if sets RegularExpression validation type. .
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_REGULAREXPRESSION {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_REGULAREXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a message to been show when control violate regular expression rule(text isn&apos;t match regular express)..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_REGULAREXPRESSIONMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_REGULAREXPRESSIONMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicfy regular expression&apos;s options..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_REGULAREXPRESSIONOPTIONS {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_REGULAREXPRESSIONOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a message to been show when control violate ruequired rule(text is empty)..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_REQUIREDMESSAGE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_REQUIREDMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more validation type. If you select &quot;None&quot;, means that controls needn&apos;t validation..
        /// </summary>
        internal static string VALIDATOR_DESCRIPTION_VALIDATION_TYPE {
            get {
                return ResourceManager.GetString("VALIDATOR_DESCRIPTION_VALIDATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator.
        /// </summary>
        internal static string VALIDATOR_NAME {
            get {
                return ResourceManager.GetString("VALIDATOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove validation infomation associate with this control?.
        /// </summary>
        internal static string VALIDATOR_REMOVEWARNING {
            get {
                return ResourceManager.GetString("VALIDATOR_REMOVEWARNING", resourceCulture);
            }
        }
    }
}
